@startmindmap

* Programming Paradigm
** Imperative
*** Structured
*** Modular
*** Object Oriented
**** Class-based
**** Prototype-based
** Declerative
*** Functional
*** Dataflow
** Logic
** Mathematical

@endmindmap